### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by ruchad** [FearlessApp/Fearless#22]
Start Activity (Harish)
Start Button 
1. Hide the button until destination is selected 
2. make the width match_parent
Map
1. Make it same as Lyft

Add Watchers (Rucha)
Move search box at top 

Chat Fragment (Herman)
1. make the width match_parent 
2. Add user profile pic
3. Show Keyboard when chat fragment is created
4. Add title and watchers 
5. Back button 

Monitor/Compose (Herman) 
1. Add color to EditText

Monitor Activity (Harish)
- Avatar and start end line for creator's trip

**Comment by hermantai** [comment]
Moved to https://github.com/FearlessApp/Fearless/issues/29
