### ISSUE TITLE
MonitorActivity - MapFragment

### ISSUE THREAD

**Issue by hermantai** [FearlessApp/Fearless#3]

**Comment by haishmg** [comment]
The functionality is working, we might have to revisit to change UX

**Comment by hermantai** [comment]
It depends how you define the "functionality". It supposes to track the user's location, e.g. if you created the trip and I stare at the map, I should see that you are moving in the map.

**Comment by haishmg** [comment]
I need to persist the user data still in Parse to do that. I will be opening another user story to do that
