### ISSUE TITLE
[Android Bootcamp] Group Project: Final app deadline 03/16

### ISSUE THREAD

**Issue by haishmg** [FearlessApp/Fearless#32]
My app is complete, please review. /cc @codepathreview @codepath

**Comment by ruchad** [comment]
https://www.dropbox.com/s/do2gx059dsl5sbk/Video%20Mar%2016%2C%206%2026%2031%20PM.mov?dl=0

**Comment by ruchad** [comment]
https://github.com/FearlessApp/Fearless/blob/master/headphone-jack-works.gif

**Comment by codepathreview** [comment]
:+1: Nice work so far on the group project. Your team has made great progress in the last week. Hope you are proud of what you have achieved in ~6 weeks.

* Good work implementing the core flows. You guys have made great progress in sprint 2 and it seems like most of your application logic is in place.
* Great contribution from everyone on the team
* Good to see you have tasks/issues being worked on actively. 
* Good to see that your team had regular commits/pull-requests to merge the code
* Keep testing your app for positive and negative scenarios and try to make sure it is crash free.
* Consult with your mentors to get their feedback as often as you can. Remember they are here to help!
* While working on polishing your app for next sprint, remember that your app follows the [android design guidelines] (http://guides.codepath.com/android/Android-Design-Guidelines) and also benchmark your app on sites such as [android app patterns] (http://www.android-app-patterns.com/) to improve the UI/UX.

Take time this week to clean up and polish your app. Generally, most of these tasks are small and easy, but go a long way in making an impact on how your app will get perceived. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Excited to see your progress next week!
